### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by dbhkhk** [icindy/wxParse#142]
wxParse版本号：0.3

input string:
```js
const testString = '<img data-ratio=\"0.6625\" data-w=\"800\" data-src=\"http://mmbiz.qpic.cn/mmbiz_jpg/RLJrD5TOPSCNkgSIBdxW2YMDslN9jWgkhMcSiaRd7AbhNm60kica4oJDnibjrU6EPIWC8yqD3iaIVtVeOeFsgRydIw/0?wx_fmt=jpeg\">';
```

报错：
> WAService.js:3 thirdScriptError
Cannot read property '0' of undefined;at pages/medium/medium onLoad function;at api request success callback function
TypeError: Cannot read property '0' of undefined
    at Object.start (http://88617949.appservice.open.weixin.qq.com/utils/wxParse/html2json.js:145:27)
    at parseStartTag (http://88617949.appservice.open.weixin.qq.com/utils/wxParse/htmlparser.js:150:13)
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at HTMLParser (http://88617949.appservice.open.weixin.qq.com/utils/wxParse/htmlparser.js:82:15)
    at Object.html2json (http://88617949.appservice.open.weixin.qq.com/utils/wxParse/html2json.js:74:5)
    at Object.wxParse (http://88617949.appservice.open.weixin.qq.com/utils/wxParse/wxParse.js:53:37)
    at success (http://88617949.appservice.open.weixin.qq.com/pages/medium/medium.js:63:17)
    at Object.success (http://88617949.appservice.open.weixin.qq.com/WAService.js:3:7592)
    at s.<anonymous> (http://88617949.appservice.open.weixin.qq.com/WAService.js:7:18056)

**Comment by dbhkhk** [comment]
刚提完issue就发现原因是img tag没有src

**Comment by MeiwahPat** [comment]
同样的问题
