### ISSUE TITLE
github 网页不能显示

### ISSUE THREAD

**Issue by quanke** [icindy/wxParse#20]
```
wx.request({
          url: "https://github.com/icindy/wxParse",
          success: function (res) {
            console.log(res.data)
            WxParse.wxParse('html',res.data.data,that)
            // 去掉注视开启多实现方式
            // WxParse.wxMoreParse('wxParseInfoData','md',res.data.data.content,self)
          }
        });
  }
```
```
WAService.js:1 TypeError: Cannot read property 'replace' of undefined
    at strNumDiscode (http://312461707.appservice.open.weixin.qq.com/wxParse/wxDiscode.js:5:14)
    at Object.strDiscode (http://312461707.appservice.open.weixin.qq.com/wxParse/wxDiscode.js:188:11)
    at Object.wxParse (http://312461707.appservice.open.weixin.qq.com/wxParse/wxParse.js:45:22)
    at Object.success (http://312461707.appservice.open.weixin.qq.com/pages/home/post/post.js:30:17)
    at Object.function.t.(anonymous function).i.(anonymous function) [as success] (http://312461707.appservice.open.weixin.qq.com/WAService.js:1:26406)
    at http://312461707.appservice.open.weixin.qq.com/WAService.js:1:26849
    at n.u (http://312461707.appservice.open.weixin.qq.com/asdebug.js:1:15610)
    at n (http://312461707.appservice.open.weixin.qq.com/asdebug.js:1:9011)
    at n.emit (http://312461707.appservice.open.weixin.qq.com/asdebug.js:1:7864)
    at window.setSecurityDetails (http://312461707.appservice.open.weixin.qq.com/asdebug.js:1:18209)
```

**Comment by icindy** [comment]
请使用标准的获取方式获取。

wxParse目前不支持直接传入网页。
具体使用方法可以下载0.3.
谢谢反馈
