### ISSUE TITLE
报错！求解 Cannot read property 'nodes' of undefined

### ISSUE THREAD

**Issue by 65man** [icindy/wxParse#296]
wxParse.js? [sm]:134 Uncaught (in promise) TypeError: Cannot read property 'nodes' of undefined
    at Object.wxParseTemArray (http://127.0.0.1:57470/appservice/plugins/wxParse/wxParse.js:179:42)
    at Home._callee6$ (http://127.0.0.1:57470/appservice/pages/home/home.js:375:39)
    at tryCatch (http://127.0.0.1:57470/appservice/npm/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (http://127.0.0.1:57470/appservice/npm/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (http://127.0.0.1:57470/appservice/npm/regenerator-runtime/runtime.js:117:21)
    at step (http://127.0.0.1:57470/appservice/pages/home/home.js:41:191)
    at http://127.0.0.1:57470/appservice/pages/home/home.js:41:361
    at <anonymous>

`let list = res.data.data
    let newinfo = []
    var that = this
    for (let i = 0; i < list.length; i++) {
      newinfo.push(list[i]['promotion_description'])
    }
    console.log(newinfo)
    for (let i = 0; i < newinfo.length; i++) {
      WxParse.wxParse('info' + i, 'html', newinfo[i], that)
      if (i === newinfo.length - 1) {
        WxParse.wxParseTemArray('acitivityArr', 'info', newinfo.length, that)
      }
    }`

**Comment by 65man** [comment]
![image](https://user-images.githubusercontent.com/22298331/46071460-a2889680-c1b2-11e8-8c7c-ef3b5f88802f.png)

**Comment by zhang463291046** [comment]
![image](https://user-images.githubusercontent.com/13843515/47473281-9c82e580-d844-11e8-8daf-9ee1cf7c2f2c.png)
添加这一行代码:that.data[bindName] = transData;
